# This is the main configuration file for your Quarto website.

project:
  type: website
  output-dir: docs

website:
  title: "MMES 565"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: appendix.qmd
        text: Appendix
format: 
  html:
    theme: cosmo
    toc: true
    toc-location: left
    mainfont: "Arial"
    css: styles.css


