---
title: "Course Schedule"
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
---

This schedule is tentative and may be adjusted throughout the semester.

---

### **Week 1: August 20**
* **R/Data Viz:** [Course Overview and Intro to R, Git and GitHub](https://drive.google.com/drive/folders/12QQgopbIIbNqcgfgNd3uNY172IEy_8YL?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course))
* **GIS:** [GIS Overview & Project Setup](https://drive.google.com/drive/folders/1xkkHP6Q8zL9xDxaKtgxIrgxPElL41iZM?usp=drive_link)

---

### **Week 2: August 27**
* **R/Data Viz:** [Data Types and Structures](https://drive.google.com/drive/folders/1tgNqKKxHsKFkgUJz6I8ZCWRoJbFX5OdY?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/data-types-and-structures))
    * **New Functions:** [`class()`](appendix.qmd#class), [`str()`](appendix.qmd#str), [`glimpse()`](appendix.qmd#glimpse), [`read_csv()`](appendix.qmd#read-csv), [`read_xlsx()`](appendix.qmd#read-xlsx), [`write_xlsx()`](appendix.qmd#write-xlsx)
* **GIS:** [Coordinate Systems and Project Setup](https://drive.google.com/drive/folders/1GzYmQZJvCCuRAmjqH6SLUDo5Oibl7DSE?usp=drive_link)

---

### **Week 3: September 3**
* **R/Data Viz:** [Wrangling with Tidyverse](https://drive.google.com/drive/folders/1F7R4cr1yaR6hpTRCzctKQkslhp_bIysB?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/wrangling-with-tidyverse))
    * **New Functions:** [`subset()`](appendix.qmd#subset), [`filter()`](appendix.qmd#filter), [`select()`](appendix.qmd#select), [`%>%`](appendix.qmd#pipe), [Logical Operators](appendix.qmd#logical-operators)
* **GIS:** [Importing, Selecting and Attributes](https://drive.google.com/drive/folders/1DRHdC14v6MwCN1hZJfHnfS2xkadauGAY?usp=drive_link)
    * **New Tools:** [`Dissolve`](appendix.qmd#dissolve), [`Excel to Table`](appendix.qmd#excel-to-table), [`XY Table to Point`](appendix.qmd#xy-table-to-point), [`Calculate Field`](appendix.qmd#calculate-field)

---

### **Week 4: September 10**
* **R/Data Viz:** [Advanced Wrangling and Joins](https://drive.google.com/drive/folders/1R7YFHEv9NhFg0fmJk0AkYABHndwY9MEQ?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/advanced-wrangling-and-joins))
    * **New Functions:** [`left_join()`](appendix.qmd#left-join), [`right_join()`](appendix.qmd#right-join), [`full_join()`](appendix.qmd#full-join), [`inner_join()`](appendix.qmd#inner-join), [`mutate()`](appendix.qmd#mutate), [`summarize()`](appendix.qmd#summarize), [`case_when()`](appendix.qmd#case-when), [`group_by()`](appendix.qmd#group-by)
* **GIS:** [Clipping, Buffering and Extracting](https://drive.google.com/drive/folders/1ZV47CRUvIInoCJko08Cx88E9XcvugXmE?usp=drive_link)
    * **New Tools:** [`Clip`](appendix.qmd#clip), [`Buffer`](appendix.qmd#buffer), [`Extract Values to Points`](appendix.qmd#extract-values-to-points), [`Hillshade`](appendix.qmd#hillshade), [Symbology](appendix.qmd#symbology)

---

### **Week 5: September 17**
* **R/Data Viz:** [Reshaping Data with Tidyverse](https://drive.google.com/drive/folders/1iAcwLf2IZbAN67WOUf_HGMWhePHCdx87?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/reshaping-data-with-tidyverse))
    * **New Functions:** [`pivot_longer()`](appendix.qmd#pivot-longer), [`pivot_wider()`](appendix.qmd#pivot-wider), [`separate()`](appendix.qmd#separate), [`unite()`](appendix.qmd#unite)
* **GIS:** [Merge, Append and Intersect](https://drive.google.com/drive/folders/1jNDzmSeX3FmY64EOZ7ga6rznoOdUKIpR?usp=drive_link)
    * **New Tools:** [`Merge`](appendix.qmd#merge), [`Append`](appendix.qmd#append), [`Intersect`](appendix.qmd#intersect), [`Spatial Join`](appendix.qmd#spatial-join)

---

### **Week 6: September 24**
* **R/Data Viz:** [Cleaning Data](https://drive.google.com/drive/folders/1Mhl9Eyr0Zfnit4OefJqfYVIFoWQ69H1f) ([GitHub Repo](https://github.com/MMES-R-Course/cleaning-data))
    * **New Functions:** [`clean_names()`](appendix.qmd#clean-names), [`str_to_lower()`](appendix.qmd#str-to-lower), [`parse_number()`](appendix.qmd#parse-number)
* **GIS:** Topic...

---

### **Week 7: October 1**
* **R/Data Viz:** [Data Visualization with ggplot](https://drive.google.com/drive/folders/1-3TfJoQKZw6X7wb9fYmnntydKlNAAn6M?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/data-visualization-with-ggplot))
    * **New Resources:** [ggplot2 Cheatsheet](https://posit.co/resources/cheatsheets/)
* **GIS:** [Extract, Convert and Tabulate](https://drive.google.com/drive/folders/1JEDysru02ZPuz88vl5t4eV7VymkWtScz?usp=drive_link)
    * **New Tools:** [`Extract by Mask`](appendix.qmd#extract-by-mask), [`Zonal Statistics`](appendix.qmd#zonal-statistics), [`Feature to Point`](appendix.qmd#feature-to-point), [`Tabulate Area`](appendix.qmd#tabulate-area)

---

### **Week 8: October 8**
* **R/Data Viz:** [Data visualizations with ggplot-part2](https://drive.google.com/drive/folders/1VQEgYhsrxzc8QLb-L0kDu700znmse7GI?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/data-visualizations-with-ggplot-part2))
    * **New Resources:** [ggplot2 Cheatsheet](https://posit.co/resources/cheatsheets/)
* **GIS:** [Raster Tools](https://drive.google.com/drive/folders/13g8uG9qdusjlZTVcLCNm-GBluuiZx7Xf?usp=drive_link)
    * **New Tools:** [`Slope`](appendix.qmd#slope-tool), [`Aspect`](appendix.qmd#aspect-tool), [`Contour`](appendix.qmd#contour-tool), [`Raster to Polygon`](appendix.qmd#raster-to-polygon), [`Raster Calculator`](appendix.qmd#raster-calculator)

---

### **Week 9: October 15**
* **R/Data Viz:** [Reproducible Reporting in R](https://drive.google.com/drive/folders/1MErK1Umq3GJEdVDvlg-b2yuqcxAkChzJ?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/reproducible-reporting-in-r))
    * **New Resources:** [Quarto Cheat Sheet](https://quarto.org/docs/tools/cheat-sheets.html), [R Markdown Cheatsheet](https://posit.co/resources/cheatsheets/)
* **GIS:** [Creating Maps](https://drive.google.com/drive/folders/1NAG4Cj_RIj5VMjpxI_-cfs421HHhhWE7?usp=drive_link)

---

### **Week 10: October 22**
* **R/Data Viz:** [Reproducible Reporting in R part2](Topic...) ([GitHub Repo](Topic...))
* **GIS:** [Creating Maps part 2](Topic...)

---

### **Week 11: October 29**
* **R/Data Viz:** [For Loops, Conditionals and Functions](https://drive.google.com/drive/folders/1tzZmqJe_4iXm5DXOuk-2ZubAwBeslPOe?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/for-loops-conditionals-functions))
    * **New Functions:** [`for()` loops](appendix.qmd#for-loop), [Conditionals: `if`, `else if`](appendix.qmd#conditionals), [`function()`](appendix.qmd#custom-function)
* **GIS:** [Creating Shapefiles and Interpolation](https://drive.google.com/drive/folders/1mxCAKU3r3JypbFA0VxqCvtKSpcgKo8nD?usp=drive_link)
    * **New Tools:** [Creating/Editing Features](appendix.qmd#creating-editing-features), [Minimum Bounding Geometry](appendix.qmd#minimum-bounding-geometry), [Create Fishnet](appendix.qmd#create-fishnet), [Interpolation Tools](appendix.qmd#interpolation-tools)

---

### **Week 12: November 5**
* **R/Data Viz:** [Custom Functions](https://drive.google.com/drive/folders/1Ej8Ha__hLZ08FAQ4o-L3iwGKDikmP2xB?usp=drive_link) ([GitHub Repo](https://github.com/MMES-R-Course/custom-functions))
    * **New Functions:** [Custom Functions](appendix.qmd#custom-function) (Review)
* **GIS:** [ModelBuilder](https://drive.google.com/drive/folders/16wIlUMFsRwua7UVN8NMaicH8ObcmnO3N?usp=drive_link)
    * **New Tools:** [ModelBuilder](appendix.qmd#model-builder)

---

<<<<<<< HEAD
### **Week 13: November 12**
=======
### **Week 12: November 6**
* **R/Data Viz:** ([GitHub Repo](https://github.com/MMES-R-Course/cleaning-data))
    * **New Functions:** [`clean_names()`](appendix.qmd#clean-names), [`str_to_lower`](appendix.qmd#str-to-lower), [`parse_number()`](appendix.qmd#parse-number)
* **GIS:** [Creating Maps](https://drive.google.com/drive/folders/1NAG4Cj_RIj5VMjpxI_-cfs421HHhhWE7?usp=drive_link)

---

### **Week 13: November 13**
>>>>>>> b36df8f44d502bd0c242becfc914ec243f2355a6
* **Open Classroom:** In-class time to work on final projects.

---

### **Week 14: November 19**
* **Open Classroom:** In-class time to work on final projects.

---

### **Week 15: November 26**
* **No Class:** Thanksgiving Holiday

---

### **Week 16: December 3**
* **Final Projects Due**